import { inspectPdf, processPdf, createDemo } from '../src/pdf.js';
import * as pdfjs from 'pdfjs-dist';
import { PDFDocument } from 'pdf-lib';
const list = document.querySelector('#results');
let passed = 0, failed = 0;
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const fixture = async name => new File([await (await fetch(`/tests/fixtures/${name}`)).arrayBuffer()], name, { type: 'application/pdf' });
const plain = await fixture('folio-plain-multipage.pdf'), encrypted = await fixture('folio-encrypted-aes256.pdf'), rotated = await fixture('folio-rotated-crop.pdf');
async function test(name, fn) { const li = document.createElement('li'); li.textContent = `RUN ${name}`; list.append(li); try { const detail = await fn(); passed++; li.textContent = `PASS ${name}${detail ? ': ' + detail : ''}`; li.className = 'pass'; } catch(e) { failed++; li.textContent = `FAIL ${name}: ${e.stack || e}`; li.className = 'fail'; } }
async function pdfText(bytes) { const task = pdfjs.getDocument({ data: bytes.slice(), isEvalSupported:false }); try { const pdf = await task.promise; let text = ''; for (let n=1;n<=pdf.numPages;n++) text += (await (await pdf.getPage(n)).getTextContent()).items.map(i=>i.str).join(' '); return { text, pages: pdf.numPages }; } finally { await task.destroy(); } }
function outputLink(bytes, name) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([bytes], {type:'application/pdf'})); a.download=name; a.textContent=name; document.querySelector('#previews').append(a); }
await test('Plain PDF preview and page count', async()=>{const info=await inspectPdf(plain);assert(info.pages===3 && info.thumbnail.startsWith('data:image/'),'Preview or count incorrect');});
await test('AES-256 PDF requests a password',async()=>assert((await inspectPdf(encrypted)).locked,'Encrypted document was not detected'));
await test('Invalid PDF is rejected',async()=>{let rejected=false;try{await inspectPdf(new File(['invalid'],'bad.pdf'));}catch{rejected=true}assert(rejected,'Invalid PDF accepted');});
await test('Wrong password has a useful error',async()=>{let error='';try{await processPdf(encrypted,{tool:'unlock',password:'incorrect'});}catch(e){error=e.message;}assert(/password/i.test(error),'Missing password error: '+error);});
await test('Unlock AES-256 retains three pages and selectable text',async()=>{const result=await processPdf(encrypted,{tool:'unlock',password:'folio-test-2026'});const doc=await PDFDocument.load(result.bytes);assert(!doc.isEncrypted,'Still encrypted');const t=await pdfText(result.bytes);assert(t.pages===3 && t.text.includes('FOLIO SELECTABLE TEXT PAGE 3'),'Text or pages lost');outputLink(result.bytes,'verified-unlocked.pdf');});
await test('Lossless compression preserves text and avoids larger output',async()=>{const result=await processPdf(plain,{tool:'compress',quality:'lossless'});assert(result.bytes.length<=plain.size,'Output grew');assert((await pdfText(result.bytes)).text.includes('FOLIO SELECTABLE TEXT PAGE 2'),'Text lost');return `${plain.size} → ${result.bytes.length} bytes`;});
await test('Balanced compression preserves text',async()=>{const result=await processPdf(plain,{tool:'compress',quality:'balanced'});assert(result.bytes.length<=plain.size,'Output grew');assert((await pdfText(result.bytes)).text.includes('FOLIO SELECTABLE TEXT PAGE 1'),'Text lost');return `${plain.size} → ${result.bytes.length} bytes`;});
await test('Scan compression reduces file and keeps page count',async()=>{const result=await processPdf(plain,{tool:'compress',quality:'small'});assert(result.bytes.length<plain.size,'Scan compression did not reduce fixture');assert((await PDFDocument.load(result.bytes)).getPageCount()===3,'Page count changed');outputLink(result.bytes,'verified-compressed.pdf');return `${plain.size} → ${result.bytes.length} bytes`;});
await test('Letter page resize keeps text and matches page orientation',async()=>{const result=await processPdf(plain,{tool:'resize',size:'letter',orientation:'auto'});const doc=await PDFDocument.load(result.bytes);for (const [i,p] of doc.getPages().entries()){const d=p.getSize();assert(Math.abs(d.width-(i===2?792:612))<.1 && Math.abs(d.height-(i===2?612:792))<.1,'Wrong Letter dimensions');}assert((await pdfText(result.bytes)).text.includes('FOLIO SELECTABLE TEXT PAGE 3'),'Resize lost text');});
await test('Rotations and cropboxes fit A4 without clipping',async()=>{const result=await processPdf(rotated,{tool:'resize',size:'a4',orientation:'auto'});const doc=await PDFDocument.load(result.bytes);const task=pdfjs.getDocument({data:result.bytes.slice()});const pdf=await task.promise;for(let i=0;i<4;i++){const size=doc.getPage(i).getSize();assert((i%2===0)===(size.height>size.width),'Rotation orientation incorrect');const p=await pdf.getPage(i+1);const v=p.getViewport({scale:.45});const canvas=document.createElement('canvas');canvas.width=v.width;canvas.height=v.height;await p.render({canvas,canvasContext:canvas.getContext('2d'),viewport:v}).promise;document.querySelector('#previews').append(canvas);}await task.destroy();outputLink(result.bytes,'verified-resized-crop.pdf');});
await test('Custom dimensions are exact',async()=>{const result=await processPdf(plain,{tool:'resize',size:'custom',width:150,height:200,orientation:'auto'});for(const p of (await PDFDocument.load(result.bytes)).getPages()){assert(Math.abs(p.getWidth()-150*72/25.4)<.01 && Math.abs(p.getHeight()-200*72/25.4)<.01,'Custom dimension mismatch');}});
await test('Cancellation rejects with AbortError',async()=>{const controller=new AbortController();controller.abort();let code='';try{await processPdf(plain,{tool:'unlock'},()=>{},controller.signal);}catch(e){code=e.name;}assert(code==='AbortError','Cancellation failed');});
await test('Sample file works',async()=>assert((await inspectPdf(await createDemo())).pages===1,'Sample invalid'));
await test('Blank pages resize without losing page count',async()=>{const source=await PDFDocument.create();source.addPage([600,800]);source.addPage([800,600]);const file=new File([await source.save()],'blank.pdf');const result=await processPdf(file,{tool:'resize',size:'a4',orientation:'auto'});const out=await PDFDocument.load(result.bytes);assert(out.getPageCount()===2,'Blank pages lost');assert(out.getPage(0).getHeight()>out.getPage(0).getWidth() && out.getPage(1).getWidth()>out.getPage(1).getHeight(),'Blank orientation mismatch');});
await test('Out-of-bounds cropbox uses visible MediaBox intersection',async()=>{const source=await PDFDocument.create();const p=source.addPage([400,600]);p.drawText('Visible page content');p.setCropBox(-200,-100,800,800);const file=new File([await source.save()],'wide-crop.pdf');const result=await processPdf(file,{tool:'resize',size:'a4',orientation:'auto'});const out=await PDFDocument.load(result.bytes);assert(out.getPage(0).getHeight()>out.getPage(0).getWidth(),'Out-of-bounds crop changed visible orientation');});
document.querySelector('#status').textContent=`${passed} passed, ${failed} failed`;
document.title=`Folio tests: ${passed} passed, ${failed} failed`;
